cookie:
  expiry_days: 360
  key: random_signature_key
  name: random_cookie_name
credentials:
  usernames:
    alexander:
      name: Alexander
      password: $2b$12$sLLBSeStFIBOKjm9s1DqM.a2TmAdqfx/xi.TvDj954HBl.hhZ8uIy
    boran:
      name: Boran
      password: $2b$12$eGuTAFGMkYLCmFVUXijL3OsTYcGXIVKBQ0zZYf9mmVCvx6uaQV2Ne
    christiaan:
      name: Christiaan
      password: $2b$12$KRAStgUuv5CBQDR00otxidn8WNT5lHaiWX6Zymy3gTr1b)AT8V2RE
    eefje:
      name: Eefje
      password: $2b$12$tb0JTdAKfc02N0DCA7imUOWgtq/u04SEcbrYDer3BxQ5TDrJyYdVe
    esther:
      name: Esther
      password: $2b$12$07zSPYmVoYVyV.aNfz25O.OAkvJzMwfDu6D1GmDxdAHusimzkIe9.
    evert:
      name: Evert
      password: $2b$12$B8EOhNxvkvr9mAU7s0t78OYOj40jJN8x.G5cfjncva/IuiRy8LHwC
    jasper:
      name: Jasper
      password: $2b$12$48Ab.GxHuTzkt3KHXgyJze4ZGQIluNE5M0ZTeO.DpYbrpSz.Gre02
    jeroen:
      name: Jeroen
      password: $2b$12$UVXZ9FzgtyafShHpnVfU1OpzKgj.j5LEuBWHoppvgLJjdkaQkcHDm
    joostD:
      name: JoostD
      password: $2b$12$HEldi4knRMic4/2Gq0qdKO9DGzlfy1KCmJNdeCB/z4nBB4/.pkdbW
    joostH:
      name: JoostH
      password: $2b$12$kbXdzqpLC/V4oXRE9B7DyuM637VBsK2y66vH8QUrLtBec2wlooCmG
    kizje:
      name: Kizje
      password: $2b$12$D1qQLQDMUagAZblmizBmmeSX0RW0t07h1uivKGS.v.vbbA5AHwTJe
    martijn:
      name: Martijn
      password: $2b$12$a99iz36jUE9QgoYG06Defu31DwRZsrQDO4luFm14MH3rynKEyhW.u
    lex:
      name: Lex
      password: $2b$12$ypcpyEjrSorYifL7SUKhxeDKJ6ETINbHQ9nnrOsi8PuHCy8zjqhwS
    olga:
      name: Olga
      password: $2b$12$uwjl.KuKHQ.1Om2Y6pplrOFBkTZvaebhjd3F07WHkezHWsC2qp91m
    olof:
      name: Olof
      password: $2b$12$E0FtCK4Xv.RLFqubyT7Ovew0dDqZTr7g9iVqI1QyLsZWR4YCSAhVG
    philippine:
      name: Philippine
      password: $2b$12$hdZA8f29NmQfLjvkr3y.qevEJLL6XhI4Owyedu9FamReqx3rVxyUm
    sjon:
      name: Sjon
      password: $2b$12$GCXXnmYL3uLiGa//DU4ov.aSH5HfL0npb4MxLJQNrBe6sdsCbtlHC
    steven:
      name: Steven
      password: $2b$12$Cj3CK/DSe7hbNNNDz/8K3eeuWo99hzLE/mmz66vDn/JJUOcKVyC4y
    stijn:
      name: Stijn
      password: $2b$12$EBYx87l9TYrJUpgtK0Hkm.R9OH674HsTWu.x0J7AGIxwgB1r8IgPe
    sven:
      name: Sven
      password: $2b$12$62R3ZqYJq6MjtP2mO90zZ.eByJ44IPb1/Q2Qk5D0nzvG6m2XFHUJS
    taj:
      name: Taj
      password: $2b$12$ELSIU26JTDAs53K.ylV/O.uwUWXmNMIqTE6SH.fPTt1bF6QeCfZXe
    wessel:
      name: Wessel
      password: $2b$12$oIPIV7blWubrmBRL0p4/..DXwuVY.SydGNvzVPt3F.zR2EQTiVAny
    zina:
      name: Zina
      password: $2b$12$gyju3m:~!GJm-YMO|K[\c4K}o2J6~-2k5h#=b0J$92fO1"3K1obWf
