credentials:
  usernames:
    alexander:
      email: alexander.hoff@nelen-schuurmans.nl
      name: Alexander
      password: Alexander # To be replaced with hashed password
    boran:
      email: boran.aydin@nelen-schuurmans.nl
      name: Boran
      password: Boran # To be replaced with hashed password
    eefje:
      email: eefje.benschop@nelen-schuurmans.nl
      name: Eefje
      password: Eefje # To be replaced with hashed password
    esther:
      email: esther.vanderlaan@nelen-schuurmans.nl
      name: Esther
      password: Esther # To be replaced with hashed password
    evert:
      email: evert.wielsma@nelen-schuurmans.nl
      name: Evert
      password: Evert # To be replaced with hashed password
    janmaarten:
      email: janmaarten.verbree@nelen-schuurmans.nl
      name: Jan-Maarten
      password: Jan-Maarten # To be replaced with hashed password
    jasper:
      email: jasper.vanlieshout@nelen-schuurmans.nl
      name: Jasper
      password: Jasper # To be replaced with hashed password
    jeroen:
      email: jeroen.dekoning@nelen-schuurmans.nl
      name: Jeroen
      password: Jeroen # To be replaced with hashed password
    joost:
      email: joost.vandijk@nelen-schuurmans.nl
      name: JoostD
      password: JoostD # To be replaced with hashed password
    joosth:
      email: joost.vanderhammen@nelen-schuurmans.nl
      name: JoostH
      password: JoostH # To be replaced with hashed password
    kizje:
      email: kizje.marif@nelen-schuurmans.nl
      name: Kizje
      password: Kizje # To be replaced with hashed password
    leendert:
      email: leendert.vanwolfswinkel@nelen-schuurmans.nl
      name: Leendert
      password: Leendert # To be replaced with hashed password
    martijn:
      email: martijn.krol@nelen-schuurmans.nl
      name: Martijn
      password: Martijn # To be replaced with hashed password
    mats:
      email: mats.kerver@nelen-schuurmans.nl
      name: Mats
      password: Mats # To be replaced with hashed password
    olga:
      email: olga.pleumeekers@nelen-schuurmans.nl
      name: Olga
      password: Olga # To be replaced with hashed password
    olof:
      email: olof.baltus@nelen-schuurmans.nl
      name: Olof
      password: Olof # To be replaced with hashed password
    philippine:
      email: phillippine.vantets@nelen-schuurmans.nl
      name: Philippine
      password: Philippine # To be replaced with hashed password
    sjon:
      email: sjon.vandijk@nelen-schuurmans.nl
      name: Sjon
      password: Sjon # To be replaced with hashed password
    steven:
      email: steven.hosper@nelen-schuurmans.nl
      name: Steven
      password: Steven # To be replaced with hashed password
    stijn:
      email: stijn.overmeen@nelen-schuurmans.nl
      name: Stijn
      password: Stijn # To be replaced with hashed password
    sven:
      email: stijn.overmeen@nelen-schuurmans.nl
      name: Sven
      password: Sven # To be replaced with hashed password
    wessel:
      email: wessel.copier@nelen-schuurmans.nl
      name: Wessel
      password: Wessel # To be replaced with hashed password
    taj:
      email: taj.devries@nelen-schuurmans.nl
      name: Taj
      password: Taj # To be replaced with hashed password

cookie:
  expiry_days: 360
  key: random_signature_key # Must be string
  name: random_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com
