[theme]

# Used to style primary interface elements. It's the color displayed most frequently across your app's
# screens and components. Examples of widgets using this color are st.slider and st.checkbox.
primaryColor = "#BDDB45" # yellowish

# Background color for the main container.
backgroundColor = "#ECE4B7" # green

# Used as the background for most widgets. Examples of widgets with this background are st.sidebar,
# st.text_input, st.date_input.
secondaryBackgroundColor =  "#eee" # greyish  "#d7ab82" # yellow <-- not enough contrast

# Font color for the page.
textColor = "#37381d" # black

# Font family (serif | sans serif | mono) for the page. Will not impact code areas.
# Default: "sans serif"
font = "sans serif"
port=8501
